// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductFlow.OnionTest.Server.Infrastructure.Context;

#nullable disable

namespace ProductFlow.OnionTest.Server.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209191021_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProductFlow.OnionTest.Server.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProductFlow.OnionTest.Server.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("888d8fcc-01c9-44e9-ba3f-e7d40e925677"),
                            Name = "Teknoloji > Laptoplar"
                        },
                        new
                        {
                            Id = new Guid("c1cc4aa4-34cd-4521-b556-b0bda41a6fc4"),
                            Name = "Erkek Giyim"
                        },
                        new
                        {
                            Id = new Guid("8f75b3b7-1b11-464d-b156-cc85bfd5827b"),
                            Name = "Araç Aksesuar"
                        });
                });

            modelBuilder.Entity("ProductFlow.OnionTest.Server.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49ff6714-386c-42d9-8742-15dce7d38833"),
                            CategoryId = new Guid("888d8fcc-01c9-44e9-ba3f-e7d40e925677"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Intel® Raptor Lake Core™ i7-13620H 10C/16T; 24MB L3; E-CORE Max 3.60GHZ P-CORE Max 4.90 GHZ; 45W",
                            ImageUrl = "https://images.pexels.com/photos/33125275/pexels-photo-33125275.jpeg",
                            Name = "Monster Notebook 16 GB RAM RTX 3050 8GM DDR6",
                            Price = 39.99m,
                            Slug = "monster-notebook-16-gb-ram-rtx-3050-8gb-ddr6",
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("83814b22-8da8-49be-892b-d87a72676788"),
                            CategoryId = new Guid("888d8fcc-01c9-44e9-ba3f-e7d40e925677"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Intel Core i5, 16 GB RAM, RTX 3050 Ti",
                            ImageUrl = "https://images.pexels.com/photos/19012051/pexels-photo-19012051.jpeg",
                            Name = "ASUS TUF Gaming F15",
                            Price = 32999m,
                            Slug = "asus-tuf-gaming-f15",
                            Stock = 6
                        },
                        new
                        {
                            Id = new Guid("c76a0448-81fe-4640-8c1f-a9ead417aa7c"),
                            CategoryId = new Guid("888d8fcc-01c9-44e9-ba3f-e7d40e925677"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Intel Core i5, 8 GB RAM, 512 GB SSD",
                            ImageUrl = "https://images.pexels.com/photos/19012056/pexels-photo-19012056.jpeg",
                            Name = "Lenovo IdeaPad 3",
                            Price = 21999m,
                            Slug = "lenovo-ideapad-3",
                            Stock = 12
                        },
                        new
                        {
                            Id = new Guid("5c1181b1-1f59-44f9-934c-04fa5b3ea21e"),
                            CategoryId = new Guid("888d8fcc-01c9-44e9-ba3f-e7d40e925677"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Apple M1 işlemci, 8 GB RAM, 256 GB SSD",
                            ImageUrl = "https://images.pexels.com/photos/19012037/pexels-photo-19012037.jpeg",
                            Name = "MacBook Air M1",
                            Price = 34999m,
                            Slug = "macbook-air-m1",
                            Stock = 5
                        },
                        new
                        {
                            Id = new Guid("6bb1b2f2-b3cd-4728-bb5e-e5466f2cf28d"),
                            CategoryId = new Guid("c1cc4aa4-34cd-4521-b556-b0bda41a6fc4"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slim fit, %100 pamuk, günlük kullanım",
                            ImageUrl = "https://images.pexels.com/photos/12446409/pexels-photo-12446409.jpeg",
                            Name = "Erkek Basic Pamuk Tişört",
                            Price = 299m,
                            Slug = "erkek-basic-pamuk-tisort",
                            Stock = 50
                        },
                        new
                        {
                            Id = new Guid("6d5700f9-19df-4edf-bbf3-0ff6c49086a1"),
                            CategoryId = new Guid("c1cc4aa4-34cd-4521-b556-b0bda41a6fc4"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Regular fit, esnek kumaş",
                            ImageUrl = "https://images.pexels.com/photos/2897533/pexels-photo-2897533.jpeg",
                            Name = "Erkek Kot Pantolon",
                            Price = 899m,
                            Slug = "erkek-kot-pantolon",
                            Stock = 30
                        },
                        new
                        {
                            Id = new Guid("be3f0b53-e83e-42e6-b67e-f2175f2ed0b9"),
                            CategoryId = new Guid("c1cc4aa4-34cd-4521-b556-b0bda41a6fc4"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kışlık, polar iç astar",
                            ImageUrl = "https://images.pexels.com/photos/15213206/pexels-photo-15213206.jpeg",
                            Name = "Erkek Kapüşonlu Sweatshirt",
                            Price = 1199m,
                            Slug = "erkek-kapusonlu-sweatshirt",
                            Stock = 20
                        },
                        new
                        {
                            Id = new Guid("3a9b38aa-b14c-4395-827e-840d8a8f035b"),
                            CategoryId = new Guid("8f75b3b7-1b11-464d-b156-cc85bfd5827b"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Havalandırma ızgarasına takılabilir",
                            ImageUrl = "https://images.pexels.com/photos/1708769/pexels-photo-1708769.jpeg",
                            Name = "Araç İçi Telefon Tutucu",
                            Price = 249m,
                            Slug = "arac-ici-telefon-tutucu",
                            Stock = 40
                        },
                        new
                        {
                            Id = new Guid("2ce54963-16b0-4782-8ad0-f0eb3932a2d7"),
                            CategoryId = new Guid("8f75b3b7-1b11-464d-b156-cc85bfd5827b"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Universal uyumlu, yıkanabilir",
                            ImageUrl = "https://images.pexels.com/photos/5625479/pexels-photo-5625479.jpeg",
                            Name = "Oto Koltuk Kılıfı Seti",
                            Price = 1599m,
                            Slug = "oto-koltuk-kilifi-seti",
                            Stock = 15
                        },
                        new
                        {
                            Id = new Guid("8cd2beb1-bfca-4656-858d-d1b9183042ef"),
                            CategoryId = new Guid("8f75b3b7-1b11-464d-b156-cc85bfd5827b"),
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Katlanabilir, çok gözlü",
                            ImageUrl = "https://images.pexels.com/photos/29807866/pexels-photo-29807866.jpeg",
                            Name = "Araç Bagaj Organizer",
                            Price = 499m,
                            Slug = "arac-bagaj-organizer",
                            Stock = 25
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ProductFlow.OnionTest.Server.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ProductFlow.OnionTest.Server.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductFlow.OnionTest.Server.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ProductFlow.OnionTest.Server.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductFlow.OnionTest.Server.Domain.Entities.Product", b =>
                {
                    b.HasOne("ProductFlow.OnionTest.Server.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductFlow.OnionTest.Server.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
